### ISSUE TITLE
`TODO`: Read article

### ISSUE THREAD

**Issue by ever0de** [ever0de/react-native-with-storybook#1]
1. [ ] <https://medium.com/react-native-seoul/making-storybook-docs-for-react-native-web-a2ae1163119e>
2. [ ] <https://marketplace.visualstudio.com/items?itemName=Orta.vscode-react-native-storybooks>
3. [ ] <https://github.com/mmazzarolo/react-native-universal-monorepo>
4. [ ] <https://medium.com/wantedjobs/lerna%EC%99%80-yarn-workspaces%EB%A5%BC-%ED%99%9C%EC%9A%A9%ED%95%9C-%ED%8C%A8%ED%82%A4%EC%A7%80-%EA%B4%80%EB%A6%AC-429d2a685486>

**Comment by ever0de** [comment]
<https://marketplace.visualstudio.com/items?itemName=Orta.vscode-react-native-storybooks>
